"use strict";
const $=(id)=>document.getElementById(id);const ids=["name","idea","users","business","langs","constraints"];
const analyze=$("analyze"),github=$("github"),copy=$("copy"),status=$("status"),spec=$("spec"),error=$("formError");
function slugify(v){return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function config(){const c=window.APP_CONFIG||{},url=String(c.SUPABASE_URL||"").replace(/\/$/,""),key=String(c.SUPABASE_ANON_KEY||"");if(!url||url.includes("VOTRE-PROJET")||!key||key.includes("VOTRE_CLE"))throw new Error("La connexion Supabase n’est pas configurée dans config.js.");return{url,key}}
function data(){return Object.fromEntries(ids.map(id=>[id,$(id).value.trim()]))}
function busy(v){analyze.disabled=v;analyze.textContent=v?"Analyse intelligente en cours…":"Analyser automatiquement"}
async function analyzeProject(){error.textContent="";const p=data();if(!p.name||p.idea.length<20){error.textContent="Renseigne le nom et décris l’idée en au moins 20 caractères.";return}try{const{url,key}=config();busy(true);status.textContent="L’IA analyse le besoin et construit le cahier des charges…";const r=await fetch(`${url}/functions/v1/analyze-project`,{method:"POST",headers:{"Content-Type":"application/json",apikey:key,Authorization:`Bearer ${key}`},body:JSON.stringify({...p,slug:slugify(p.name)})});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out.error||`Erreur d’analyse (${r.status})`);if(!out.specification)throw new Error("L’IA n’a pas renvoyé de cahier des charges.");spec.textContent=out.specification;status.textContent=`${p.name} — cahier complet généré par l’IA, à valider.`;copy.disabled=false;github.disabled=false;localStorage.setItem("factory-project",JSON.stringify({...p,specification:out.specification}))}catch(e){error.textContent=e.message||"Analyse impossible.";status.textContent="Échec de l’analyse. Vérifie la configuration puis réessaie."}finally{busy(false)}}
async function copySpec(){try{await navigator.clipboard.writeText(spec.textContent);status.textContent="Cahier des charges copié."}catch(_){status.textContent="Sélectionne le cahier pour le copier manuellement."}}
function openGitHub(){const n=$("name").value.trim(),repo=slugify(n)||"nouveau-projet",url=`https://github.com/new?name=${encodeURIComponent(repo)}&description=${encodeURIComponent(`Application ${n} générée par Application Factory`)}`;window.open(url,"_blank","noopener,noreferrer");status.textContent="GitHub ouvert. La création automatique par API sera activée au prochain jalon."}
analyze.addEventListener("click",analyzeProject);copy.addEventListener("click",copySpec);github.addEventListener("click",openGitHub);
try{const s=JSON.parse(localStorage.getItem("factory-project")||"null");if(s){ids.forEach(id=>{if(s[id])$(id).value=s[id]});if(s.specification){spec.textContent=s.specification;status.textContent=`${s.name} — projet restauré.`;copy.disabled=false;github.disabled=false}}}catch(_){localStorage.removeItem("factory-project")}
