const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json"}});
const clean=(v:unknown,max=5000)=>typeof v==="string"?v.trim().slice(0,max):"";
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return reply({error:"Méthode non autorisée"},405);try{
const b=await req.json(),p={name:clean(b.name,120),slug:clean(b.slug,120),idea:clean(b.idea),users:clean(b.users,1000),business:clean(b.business,1000),langs:clean(b.langs,500),constraints:clean(b.constraints,2000)};if(!p.name||p.idea.length<20)return reply({error:"Projet incomplet"},400);
const key=Deno.env.get("GEMINI_API_KEY"),model=Deno.env.get("GEMINI_MODEL")||"gemini-2.5-flash";if(!key)return reply({error:"Le secret GEMINI_API_KEY est absent dans Supabase"},500);
const prompt=`Tu es directeur produit, architecte logiciel, UX designer, expert sécurité et responsable qualité. Transforme le besoin suivant en cahier des charges commercial complet, précis et directement exploitable. Comprends librement le secteur : aucun modèle métier n'est pré-écrit. N'invente pas une demande contraire au besoin et signale tes hypothèses.
PROJET\nNom : ${p.name}\nIdée : ${p.idea}\nUtilisateurs : ${p.users||"À déduire"}\nModèle économique : ${p.business||"À proposer avec prudence"}\nLangues : ${p.langs||"Français"}\nContraintes : ${p.constraints||"À identifier"}
Rédige en français et en Markdown avec ces sections : 1 Résumé et problème résolu ; 2 Objectifs, périmètre inclus et exclusions ; 3 Profils, rôles et permissions ; 4 Parcours utilisateurs ; 5 Fonctionnalités par module avec règles et statuts ; 6 Écrans ; 7 Back-office ; 8 Modèle économique si pertinent ; 9 Tables, champs et relations ; 10 API, intégrations et notifications ; 11 Architecture web/mobile, Supabase, GitHub, Cloudflare ; 12 Sécurité, RLS, confidentialité, conformité et sauvegardes ; 13 Multilingue, accessibilité, performance et réseau faible ; 14 Critères d'acceptation vérifiables ; 15 Tests fonctionnels, sécurité et permissions ; 16 Données de démonstration ; 17 Jalons cumulatifs de 0 à 100 % avec livrable et validation ; 18 Risques, dépendances, coûts et décisions ; 19 Définition exacte de la version commerciale à 100 %. Sois spécifique, cohérent et assez détaillé pour générer le SQL et l'application. Termine par STATUT : CAHIER DES CHARGES À VALIDER.`;
const g=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify({contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{temperature:.25,maxOutputTokens:8192}})}),out=await g.json();if(!g.ok)return reply({error:out?.error?.message||"Erreur Gemini"},502);const specification=out?.candidates?.[0]?.content?.parts?.map((x:{text?:string})=>x.text||"").join("\n").trim();if(!specification)return reply({error:"Réponse IA vide"},502);
const base=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(base&&service)await fetch(`${base}/rest/v1/projects`,{method:"POST",headers:{apikey:service,Authorization:`Bearer ${service}`,"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({name:p.name,slug:p.slug,idea:p.idea,languages:p.langs,status:"analyzed",specification:{markdown:specification}})});
return reply({specification,model});}catch(e){return reply({error:e instanceof Error?e.message:"Erreur interne"},500)}});
